### ISSUE TITLE
Crash when PX_DELETE(mNPhaseCore) is called in Sc::Scene::release()

### ISSUE THREAD

**Issue by PhilNad** [NVIDIA-Omniverse/PhysX#222] opened 2023-12-03 22:28 UTC
### Library and Version

PhysX SDK 5.2.1

### Operating System

Ubuntu 20.04

### Steps to Trigger Behavior

 1. Create a lot of kinematic shapes attached to actors that are put in contact with each other, and with `kineKineFilteringMode = PxPairFilteringMode::eKEEP`.
 2. Simulate and fetchResults.
 3. Call PX_RELEASE(gScene)
 4. Systematic crash when PX_DELETE(mNPhaseCore) is called in Sc::Scene::release()

### Code Snippet to Reproduce Behavior
Unfortunately, I was not able to produce a minimal working example that would trigger the behavior. However, this is the call stack that I get every time from my (much larger) project. I noticed that, in order to trigger the segmentation fault, a minimal number of shapes had to be added to the scene (i.e. when ran with fewer shapes, the condition was not triggered). 
```
physx::PxPoolBase<physx::Sc::ActorPair, physx::PxReflectionAllocator<physx::Sc::ActorPair> >::disposeElements(physx::PxPoolBase<physx::Sc::ActorPair, physx::PxReflectionAllocator<physx::Sc::ActorPair> > * this) (/PhysX/physx/include/foundation/PxPool.h:225)
physx::PxPoolBase<physx::Sc::ActorPair, physx::PxReflectionAllocator<physx::Sc::ActorPair> >::~PxPoolBase(physx::PxPoolBase<physx::Sc::ActorPair, physx::PxReflectionAllocator<physx::Sc::ActorPair> > * this) (/PhysX/physx/include/foundation/PxPool.h:71)
physx::Sc::NPhaseCore::~NPhaseCore(physx::Sc::NPhaseCore * this) (/PhysX/physx/source/simulationcontroller/src/ScNPhaseCore.cpp:68)
physx::Sc::Scene::release(physx::Sc::Scene * this) (/PhysX/physx/source/simulationcontroller/src/ScScene.cpp:1100)
physx::NpScene::~NpScene(physx::NpScene * this) (/PhysX/physx/source/physx/src/NpScene.cpp:259)
physx::NpScene::~NpScene(physx::NpScene * this) (/PhysX/physx/source/physx/src/NpScene.cpp:198)
physx::NpPhysics::releaseSceneInternal(physx::NpPhysics * this, physx::PxScene & scene) (/PhysX/physx/source/physx/src/NpPhysics.cpp:425)
PX_RELEASE(gScene)
```
Let me know if there is anything I can test.

### Expected Behavior

Release the scene without crashing.

### Actual Behavior

Crashes 100% of the time.

**Comment by preist-nvidia** [comment] 2023-12-11 13:44
Thank you for the report! We'll have a look. Internal tracking: PX-4672

**Comment by adenzler-nvidia** [comment] 2023-12-14 11:15
Thanks for the report! I'm trying to reproduce this but my first attempts are failing, but I'm on windows right now. Will try linux later. Could you maybe give me a hint about the order of magnitude of the number of shapes? Did you have additional actors in the scene, and if so, what kind? Are you using GPU dynamics?

**Comment by adenzler-nvidia** [comment] 2023-12-20 09:19
Thank you very much for the detailed repro snippet - I can reproduce the crash on my machine now. Interestingly, if you run this in debug config you'll hit an assert much earlier in ScNphaseCore::resizeContactReportPairData because the paircount overflows a 16bit variable. I'll have a closer look and get back to you with a potential fix/workaround.

**Comment by adenzler-nvidia** [comment] 2024-01-10 08:33
Hi @PhilNad - thanks again for the repro snippet. A fix for this crash will be in the next release.

For a workaround, I suggest using more actors with each one having fewer shapes attached, such that the total number of colliding shapes per actor pair does not exceed 65536 shape pairs.

**Closed as completed by adenzler-nvidia** 2024-01-10 08:33 UTC
